=== aptree-labs/campaign-registry/campaign.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#", 
    "type": "object",
    "definitions": {
        "queryFilter": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "eq": {},
                "neq": {}, 
                "gt": {
                    "type": "number"
                },
                "lt": {
                    "type": "number"
                },
                "in": {
                    "type": "array"
                },
                "and": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/queryFilter"
                    }
                },
                "or": {
                    "type": "array", 
                    "items": {
                        "$ref": "#/definitions/queryFilter"
                    }
                },
                "not": {
                    "$ref": "#/definitions/queryFilter"
                }
            },
            "additionalProperties": false
        }
    },
    "properties": {
        "id": {
            "type": "string"
        },
        "title":{
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "start_at": {
            "type": "number"
        },
        "end_at": {
            "type": "number"
        },
        "status": {
            "type":  "string",
            "enum": [
                "active",
                "inactive",
                "completed"
            ]
        },
        "platform": {
            "type": "string"
        },
        "functions": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "entry_function": { 
                        "type": "string"
                    },
                    "is_script": {
                        "type": "boolean"
                    },
                    "events": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "type": "string"
                                },
                                "rewards": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "id": {"type": "string"},
                                            "check_eligibility": {
                                                "$ref": "#/definitions/queryFilter"
                                            },
                                            "check_payload": {
                                                "$ref": "#/definitions/queryFilter"
                                            },
                                            "droplets": {
                                                "type": "number"
                                            },
                                            "max_rewards": {
                                                "type": "number",
                                                "description": "The max number of times the user can be rewarded for this campaign having met the reward criteria"
                                            }
                                        }
                                    }
                                },
                                "is_proxy": {
                                    "type": "boolean"
                                }
                            },
                            "required": ["name", "rewards"]
                        }
                    },
                    "name": {"type": "string"},
                    "description": {"type": "string"},
                    "is_duplicate": {"type": "boolean"},
                    "link": {"type": "string"}
                }
            }
        },
        "referral_link": {
            "type": "string"
        },
        "network": {
            "type": "string",
            "enum": ["testnet", "mainnet"]
        },
        "category": {
            "type": "string",
            "enum": [
                "swap",
                "liquidity"
            ]
        },
        "filters": {
            "type": "array",
            "description": "A way to simplify categorisation to easily configure how campaigns will be filtered by end users",
            "items": {
                "type": "string"
            }
        },
        "action_tags": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": [
        "id",
        "title",
        "description",
        "start_at",
        "end_at",
        "status",
        "platform",
        "referral_link",
        "functions",
        "action_tags"
    ],
    "remove": {
      "type": "boolean"
    }
}

=== aptree-labs/campaign-registry/campaigns/5.campaign.json
{
    "id": "5",
    "title": "Cellana Panorama",
    "description": "Stake on Cellana for a rich panorama; droplets paint a green diorama.",
    "start_at": 1754221472038,
    "end_at": 1785757217018,
    "status": "active",
    "platform": "cellana",
    "referral_link": "https://cellana.finance/",
    "functions": [
        {
            "entry_function": "0x4bf51972879e3b95c4781a5cdcb9e1ee24ef483e7d22f2d903626f126df62bd1::router::swap_route_entry_from_coin",
            "events": [
                {
                    "name": "0x4bf51972879e3b95c4781a5cdcb9e1ee24ef483e7d22f2d903626f126df62bd1::liquidity_pool::SwapEvent",
                    "rewards": [
                        {
                            "id": "c1",
                            "droplets":200
                        }
                    ]
                }
            ],
            "name": "Swap",
            "description": "Swap any asset pair on Cellana"
        },
        {
            "entry_function": "0x4bf51972879e3b95c4781a5cdcb9e1ee24ef483e7d22f2d903626f126df62bd1::router::create_pool_both_coins",
            "events": [
                {
                    "name": "0x4bf51972879e3b95c4781a5cdcb9e1ee24ef483e7d22f2d903626f126df62bd1::liquidity_pool::CreatePoolEvent",
                    "rewards": [
                        {
                            "id": "c2",
                            "droplets":500
                        }
                    ]
                }
            ],
            "name": "Create Pool",
            "description": "Create a pool on Cellana"
        },
        {
            "entry_function": "0x4bf51972879e3b95c4781a5cdcb9e1ee24ef483e7d22f2d903626f126df62bd1::router::add_liquidity_and_stake_both_coins_entry",
            "events": [
                {
                    "name": "0x4bf51972879e3b95c4781a5cdcb9e1ee24ef483e7d22f2d903626f126df62bd1::liquidity_pool::AddLiquidityEvent",
                    "rewards": [
                        {
                            "id": "c3",
                            "droplets": 500
                        }
                    ]
                }
            ],
            "name": "Deposit Liquidity",
            "description": "Deposit to a liquidity pool on Cellana"
        },
        {
            "entry_function": "0x4bf51972879e3b95c4781a5cdcb9e1ee24ef483e7d22f2d903626f126df62bd1::router::add_liquidity_and_stake_entry",
            "events": [
                {
                    "name": "0x4bf51972879e3b95c4781a5cdcb9e1ee24ef483e7d22f2d903626f126df62bd1::gauge::StakeEvent",
                    "rewards": [
                        {
                            "id": "c4",
                            "droplets": 500
                        }
                    ]
                }
            ],
            "name": "Stake",
            "description": "Stake on Cellana"
        }
    ],
    "action_tags": [
        "swap",
        "create-pool",
        "add-liquidity",
        "stake"
    ]
}

=== aptree-labs/campaign-registry/campaigns/6.campaign.json
{
    "id": "6",
    "title": "Echelon Resonance",
    "description": "Loop your APT for deep resonance; droplets drum in perfect consonance.",
    "start_at": 1754221472038,
    "end_at": 1785757217018,
    "status": "active",
    "platform": "echelon",
    "referral_link": "https://app.echelon.market/markets?network=aptos_mainnet",
    "functions": [
        {
            "entry_function": "0xc6bc659f1649553c1a3fa05d9727433dc03843baac29473c817d06d39e7621ba::scripts::supply_fa", 
            "events": [
                {
                    "name": "0xc6bc659f1649553c1a3fa05d9727433dc03843baac29473c817d06d39e7621ba::lending::SupplyEvent",
                    "rewards": [
                        {
                            "id": "e1",
                            "droplets": 500
                        }
                    ]
                }
            ],
            "name": "Supply Liquidity on Echelon",
            "description": "Deposit Liquidity on any pool"
        },
        {
            "entry_function": "0xc6bc659f1649553c1a3fa05d9727433dc03843baac29473c817d06d39e7621ba::scripts::supply",
            "events": [
                {
                    "name": "0xc6bc659f1649553c1a3fa05d9727433dc03843baac29473c817d06d39e7621ba::lending::SupplyEvent",
                    "rewards": [
                        {
                            "id": "e2",
                            "droplets": 500
                        }
                    ]
                }
            ],
            "is_duplicate": true
        },
        {
            "entry_function": "0x024c90c44edf46aa02c3e370725b918a59c52b5aa551388feb258bd5a1e82271::isolated_lending::add_collateral",
            "events": [
                {
                    "name": "0x24c90c44edf46aa02c3e370725b918a59c52b5aa551388feb258bd5a1e82271::isolated_lending::AddCollateralEvent",
                    "rewards": [
                        {
                            "id": "e3",
                            "droplets": 500
                        }
                    ]
                }
            ],
            "name": "Lending",
            "description": "",
            "is_duplicate": true
        },
        {
            "entry_function": "0xc6bc659f1649553c1a3fa05d9727433dc03843baac29473c817d06d39e7621ba::scripts::borrow_fa",
            "events": [
                {
                    "name": "0xc6bc659f1649553c1a3fa05d9727433dc03843baac29473c817d06d39e7621ba::lending::BorrowEvent",
                    "rewards": [
                        {
                            "id": "e2",
                            "droplets": 800
                        }
                    ]
                }
            ],
            "name": "Borrow on Echelon",
            "description": ""
        }
    ],
    "action_tags": [
        "supply-liquidity", "deposit-collateral"
    ]
}

=== aptree-labs/campaign-registry/campaigns/11.campaign.json
{
    "id": "11",
    "title": "Tapp Recap",
    "description": "Spin pools, then take the recap; droplets tap roots in rhythmic clap.",
    "start_at": 1754221472038,
    "end_at": 1785757217018,
    "status": "active",
    "platform": "tapp",
    "referral_link": "https://tapp.exchange/swap",
    "functions": [
        {
            "entry_function": "0x487e905f899ccb6d46fdaec56ba1e0c4cf119862a16c409904b8c78fab1f5e8a::router::swap",
            "events": [
                {
                    "name": "0x487e905f899ccb6d46fdaec56ba1e0c4cf119862a16c409904b8c78fab1f5e8a::router::Swapped",
                    "rewards": [
                        {
                            "id": "t1",
                            "droplets": 100
                        }
                    ]
                }
            ],
            "name": "Swap on Tapp Exchange"
        },
        {
            "entry_function": "0x487e905f899ccb6d46fdaec56ba1e0c4cf119862a16c409904b8c78fab1f5e8a::router::create_pool_add_liquidity",
            "events": [
                {
                    "name": "0x487e905f899ccb6d46fdaec56ba1e0c4cf119862a16c409904b8c78fab1f5e8a::router::PoolCreated",
                    "rewards": [
                        {
                            "id": "t2",
                            "droplets": 500
                        }
                    ]
                },
                {
                    "name": "0x487e905f899ccb6d46fdaec56ba1e0c4cf119862a16c409904b8c78fab1f5e8a::router::LiquidityAdded",
                    "rewards": [
                        {
                            "id": "t3",
                            "droplets": 500
                        }
                    ]
                }
            ],
            "name": "Create a Liquidity Pool"
        },
        {
            "entry_function": "0x487e905f899ccb6d46fdaec56ba1e0c4cf119862a16c409904b8c78fab1f5e8a::router::add_liquidity",
            "events": [
                {
                    "name": "0x487e905f899ccb6d46fdaec56ba1e0c4cf119862a16c409904b8c78fab1f5e8a::router::LiquidityAdded",
                    "rewards": [
                        {
                            "id": "t4",
                            "droplets": 500
                        }
                    ]
                }
            ],
            "name": "Provide Liquidity on Tapp Exchange"
        }
    ],
    "action_tags": [
        "create-pool",
        "add-liquidity",
        "swap"
    ]
}

=== aptree-labs/campaign-registry/campaigns/4.campaign.json
{
    "id": "4",
    "title": "Aries Campaign",
    "description": "Trade and lend with blazing flare; droplets spark your tree up there.",
    "start_at": 1754221472038,
    "end_at": 1785757217018,
    "status": "active",
    "platform": "aries",
    "referral_link": "https://app.ariesmarkets.xyz/lending",
    "functions": [
        {
            "entry_function": "0x9770fa9c725cbd97eb50b2be5f7416efdfd1f1554beb0750d4dae4c64e860da3::controller::deposit_fa",
            "events": [
                {
                    "name": "0x9770fa9c725cbd97eb50b2be5f7416efdfd1f1554beb0750d4dae4c64e860da3::profile::SyncProfileDepositEvent",
                    "rewards": [
                        {
                            "id": "a1",
                            "droplets": 500
                        }
                    ]
                }
            ],
            "name": "Supply liquidity on Aries",
            "description": "Supply liquidity on Aries"
        },
        {
            "entry_function": "0x9770fa9c725cbd97eb50b2be5f7416efdfd1f1554beb0750d4dae4c64e860da3::controller::deposit",
            "events": [
                {
                    "name": "0x9770fa9c725cbd97eb50b2be5f7416efdfd1f1554beb0750d4dae4c64e860da3::profile::SyncProfileDepositEvent",
                    "rewards": [
                        {
                            "id": "a1",
                            "droplets": 500
                        }
                    ]
                }
            ],
            "is_duplicate": true
        },
        {
            "entry_function": "0x9770fa9c725cbd97eb50b2be5f7416efdfd1f1554beb0750d4dae4c64e860da3::controller::withdraw_fa",
            "events": [
                {
                    "name": "0x9770fa9c725cbd97eb50b2be5f7416efdfd1f1554beb0750d4dae4c64e860da3::profile::SyncProfileBorrowEvent",
                    "rewards": [
                        {
                            "id": "a1",
                            "droplets": 800
                        }
                    ]
                }
            ],
            "name": "Borrow on Aries",
            "description": ""
        }
    ],
    "action_tags": [
        "deposit-liquidity"
    ]
}

=== aptree-labs/campaign-registry/campaigns/20.campaign.json
{
  "id": "20",
  "title": "Aptree Christmas Special",
  "description": "The leaves on the forest trees are heavy with snow, where are the elves?, they should be ready to go!",
  "start_at": 1765238400000,
  "end_at": 1765929599000,
  "status": "active",
  "platform": "aptree",
  "referral_link": "https://aptree.io/christmas",
  "action_tags": [],
  "functions": [
        {
            "entry_function": "0x487e905f899ccb6d46fdaec56ba1e0c4cf119862a16c409904b8c78fab1f5e8a::router::swap",
            "events": [
                {
                    "name": "0x487e905f899ccb6d46fdaec56ba1e0c4cf119862a16c409904b8c78fab1f5e8a::router::Swapped",
                    "rewards": [
                        {
                            "id": "tgp",
                            "droplets": 1
                        }
                    ]
                }
            ],
            "name": "Tapp Christmas Swap",
            "description": "Swap 5 times on tapp exchange to get a special present."
        },
        {
            "entry_function": "0x7bd64a730c360a87da24187d6d2e9128310ff25419facb3000d6b2293a06280a::entry::execute_routes",
            "events": [
                {
                    "name": "0x487e905f899ccb6d46fdaec56ba1e0c4cf119862a16c409904b8c78fab1f5e8a::router::Swapped",
                    "rewards": [
                        {
                            "id": "tgp",
                            "droplets": 1
                        }
                    ]
                }
            ],
            "name": "Tapp Christmas Swap",
            "is_duplicate": true
        },
        {
            "entry_function": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::router_v3::swap_batch_coin_entry",
            "events": [
                {
                    "name": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::SwapEventV3",
                    "rewards": [
                        {
                            "id": "hgp",
                            "droplets":1
                        }
                    ]
                }
            ],
            "name": "Hyperion Holiday Swap", 
            "description": "Swap 5 times on Hyperion to for santa to bring you a special reward."
        },
        {
            "entry_function": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::router_v3::swap_batch_coin_directly_deposit_entry",
            "events": [
                {
                    "name": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::SwapEventV3",
                    "rewards": [
                        {
                            "id": "hgp",
                            "droplets":1
                        }
                    ]
                }
            ],
            "name": "Hyperion Holiday Swap", 
            "is_duplicate": true
        },
        {
            "entry_function": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::router_v3::swap_batch_coin_directly_deposit_entry",
            "events": [
                {
                    "name": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::SwapEventV3",
                    "rewards": [
                        {
                            "id": "hgp",
                            "droplets":1
                        }
                    ]
                }
            ],
            "name": "Hyperion Holiday Swap", 
            "is_duplicate": true
        },
        {
            "entry_function": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::router_v3::swap_batch_directly_deposit",
            "events": [
                {
                    "name": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::SwapEventV3",
                    "rewards": [
                        {
                            "id": "hgp",
                            "droplets":1
                        }
                    ]
                }
            ],
            "name": "Hyperion Holiday Swap", 
            "is_duplicate": true
        },
        {
          "entry_function": "0x1::aptos_account::transfer_coins",
          "events": [
            {
              "name": "0x1::fungible_asset::Deposit",
              "rewards": [
                {
                  "id": "pgp",
                  "droplets": 1
                }
              ]
            }
          ],
          "name": "Petra Presents Premier",
          "description": "Send money to 5 friends with petra to get a present."
        },
        {
          "entry_function": "0x1::aptos_account::transfer_fungible_assets",
          "events": [
            {
              "name": "0x1::fungible_asset::Deposit",
              "rewards": [
                {
                  "id": "pgp",
                  "droplets": 1
                }
              ]
            }
          ],
          "is_duplicate": true,
          "name": "Petra Presents Premier"
        }
        
     ]
}

=== aptree-labs/campaign-registry/campaigns/12.campaign.json
{
    "id": "12",
    "title": "Thala Gala",
    "description": "Mint and stake at the Thala gala; droplets flow like a moonlit raga.",
    "start_at": 1754221472038,
    "end_at": 1785757217018,
    "status": "active",
    "platform": "thala",
    "referral_link": "https://www.thala.fi/",
    "functions": [
        {
            "entry_function": "0x007730cd28ee1cdc9e999336cbc430f99e7c44397c0aa77516f6f23a78559bb5::coin_wrapper::add_liquidity_stable",
            "events": [
                {
                    "name": "0x7730cd28ee1cdc9e999336cbc430f99e7c44397c0aa77516f6f23a78559bb5::pool::AddLiquidityEvent",
                    "rewards": [
                        {
                            "id": "th1",
                            "droplets": 500
                        }
                    ]
                }
            ],
            "name": "Add Liquidity"
        },
        {
            "entry_function": "0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::scripts::stake_APT",
            "events": [
                {
                    "name": "0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::StakeAPTEvent",
                    "rewards": [
                        {
                            "id": "th2",
                            "droplets": 500
                        }
                    ]
                }
            ],
            "name": "Stake APT"
        },
        {
            "entry_function": "0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::scripts::stake_APT_and_thAPT",
            "events": [
                {
                    "name": "0xfaf4e633ae9eb31366c9ca24214231760926576c7b625313b3688b5e900731f6::staking::StakeAPTEvent", 
                    "rewards": [
                        {
                            "id": "th3",
                            "droplets": 500
                        }
                    ]
                }
            ],
            "is_duplicate": false
        }
    ],
    "action_tags": [
        "stake",
        "deposit-liquidity"
    ]
}

=== aptree-labs/campaign-registry/campaigns/14.campaign.json
{
    "id": "14",
    "title": "Amnis Oasis",
    "description": "Liquid-stake APT in the oasisâ€”droplets raise your yield basis.",
    "start_at": 1754221472038,
    "end_at": 1785757217018,
    "status": "active",
    "platform": "amnis",
    "referral_link": "https://amnis.finance/",
    "functions": [
        {
            "entry_function": "0x111ae3e5bc816a5e63c2da97d0aa3886519e0cd5e4b046659fa35796bd11542a::router::deposit_entry",
            "events": [
                {
                    "name": "0x1::stake::AddStake",
                    "rewards": [
                        {
                            "id": "amn1",
                            "droplets": 500
                        }
                    ]
                },
                {
                    "name": "0x111ae3e5bc816a5e63c2da97d0aa3886519e0cd5e4b046659fa35796bd11542a::router::MintEvent",
                    "rewards": [
                        {
                            "id": "am4",
                            "droplets": 500
                        }
                    ]
                },
                {
                    "name": "0x111ae3e5bc816a5e63c2da97d0aa3886519e0cd5e4b046659fa35796bd11542a::stapt_token::BurnEvent",
                    "rewards": [
                        {
                            "id": "am5",
                            "droplets": 500
                        }
                    ]
                }
            ],
            "name": "Stake amAPT for stAPT",
            "link": "https://stake.amnis.finance/stake"
        },
        {
            "entry_function": "0x111ae3e5bc816a5e63c2da97d0aa3886519e0cd5e4b046659fa35796bd11542a::router::deposit_and_stake_entry",
            "events": [
                {
                    "name": "0x111ae3e5bc816a5e63c2da97d0aa3886519e0cd5e4b046659fa35796bd11542a::router::StakeEvent",
                    "rewards": [
                        {
                            "id": "amn2",
                            "droplets": 500
                        }
                    ]
                },
                {
                    "name": "0x111ae3e5bc816a5e63c2da97d0aa3886519e0cd5e4b046659fa35796bd11542a::router::MintEvent",
                    "rewards": [
                        {
                            "id": "am4",
                            "droplets": 500
                        }
                    ]
                }
            ],
            "is_duplicate":true
        },
        {
            "entry_function": "0x111ae3e5bc816a5e63c2da97d0aa3886519e0cd5e4b046659fa35796bd11542a::router::stake_entry",
            "events": [
                {
                    "name": "0x111ae3e5bc816a5e63c2da97d0aa3886519e0cd5e4b046659fa35796bd11542a::router::StakeEvent",
                    "rewards": [
                        {
                            "id": "am3",
                            "droplets": 500
                        }
                    ]
                },
                {
                    "name": "0x111ae3e5bc816a5e63c2da97d0aa3886519e0cd5e4b046659fa35796bd11542a::router::MintEvent",
                    "rewards": [
                        {
                            "id": "am4",
                            "droplets": 500
                        }
                    ]
                }
            ],
            "name": "Mint amAPT",
            "link": "https://stake.amnis.finance/mint"
        }
    ],
    "action_tags": [
        "stake"
    ]
}
