=== aptree-labs/campaign-registry/campaign.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#", 
    "type": "object",
    "definitions": {
        "queryFilter": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "eq": {},
                "neq": {}, 
                "gt": {
                    "type": "number"
                },
                "lt": {
                    "type": "number"
                },
                "in": {
                    "type": "array"
                },
                "and": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/queryFilter"
                    }
                },
                "or": {
                    "type": "array", 
                    "items": {
                        "$ref": "#/definitions/queryFilter"
                    }
                },
                "not": {
                    "$ref": "#/definitions/queryFilter"
                }
            },
            "additionalProperties": false
        }
    },
    "properties": {
        "id": {
            "type": "string"
        },
        "title":{
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "start_at": {
            "type": "number"
        },
        "end_at": {
            "type": "number"
        },
        "status": {
            "type":  "string",
            "enum": [
                "active",
                "inactive",
                "completed"
            ]
        },
        "platform": {
            "type": "string"
        },
        "functions": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "entry_function": { 
                        "type": "string"
                    },
                    "is_script": {
                        "type": "boolean"
                    },
                    "events": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "type": "string"
                                },
                                "rewards": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "id": {"type": "string"},
                                            "check_eligibility": {
                                                "$ref": "#/definitions/queryFilter"
                                            },
                                            "check_payload": {
                                                "$ref": "#/definitions/queryFilter"
                                            },
                                            "droplets": {
                                                "type": "number"
                                            },
                                            "max_rewards": {
                                                "type": "number",
                                                "description": "The max number of times the user can be rewarded for this campaign having met the reward criteria"
                                            }
                                        }
                                    }
                                },
                                "is_proxy": {
                                    "type": "boolean"
                                }
                            },
                            "required": ["name", "rewards"]
                        }
                    },
                    "name": {"type": "string"},
                    "description": {"type": "string"},
                    "is_duplicate": {"type": "boolean"},
                    "link": {"type": "string"}
                }
            }
        },
        "referral_link": {
            "type": "string"
        },
        "network": {
            "type": "string",
            "enum": ["testnet", "mainnet"]
        },
        "category": {
            "type": "string",
            "enum": [
                "swap",
                "liquidity"
            ]
        },
        "filters": {
            "type": "array",
            "description": "A way to simplify categorisation to easily configure how campaigns will be filtered by end users",
            "items": {
                "type": "string"
            }
        },
        "action_tags": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": [
        "id",
        "title",
        "description",
        "start_at",
        "end_at",
        "status",
        "platform",
        "referral_link",
        "functions",
        "action_tags"
    ],
    "remove": {
      "type": "boolean"
    }
}

=== aptree-labs/campaign-registry/campaigns/2.campaign.json
{
    "id": "2",
    "network": "mainnet",
    "title": "Hyperion Horizon", 
    "description": "Cast liquidity toward the horizon; droplets rise, roots start upris'n.",
    "platform": "hyperion",
    "start_at": 1751888498347,
    "end_at": 1785757217018,
    "referral_link": "https://hyperion.xyz/swap?from=0x1::aptos_coin::AptosCoin&to=0x435ad41e7b383cef98899c4e5a22c8dc88ab67b22f95e5663d6c6649298c3a9d",
    "status": "active",
    "functions": [
        {
            "entry_function": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::router_v3::swap_batch_coin_entry",
            "events": [
                {
                    "name": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::SwapEventV3",
                    "rewards": [
                        {
                            "id": "h1",
                            "droplets":200
                        }
                    ]
                }
            ]
        },
        {
            "entry_function": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::router_v3::swap_batch_coin_directly_deposit_entry",
            "events": [
                {
                    "name": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::SwapEventV3",
                    "rewards": [
                        {
                            "id": "h1",
                            "droplets":200
                        }
                    ]
                }
            ]
        },
        {
            "entry_function": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::router_adapter::create_liquidity_entry",
            "events": [
                {
                    "name": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::AddLiquidityEventV2",
                    "rewards": [
                        {
                            "id": "h4",
                            "droplets": 400
                        }
                    ]
                }
            ]
        },
        {
            "entry_function": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::router_adapter::create_liquidity_coin_entry",
            "events": [
                {
                    "name": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::AddLiquidityEventV3",
                    "rewards": [
                        {
                            "id": "h8",
                            "droplets": 500
                        }
                    ]
                },
                {
                    "name": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::CreatePoolEvent", 
                    "rewards": [
                        {
                            "id": "h7",
                            "droplets": 500
                        }
                    ]
                }
            ]
        },
        {
            "entry_function": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::router_adapter::create_liquidity_both_coin_entry",
            "events": [
                {
                    "name": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::AddLiquidityEventV3",
                    "rewards": [
                        {
                            "id": "h2",
                            "droplets": 500
                        }
                    ]
                },
                {
                    "name": "0x8b4a2c4bb53857c718a04c020b98f8c2e1f99a68b0f57389a8bf5434cd22e05c::pool_v3::CreatePoolEvent", 
                    "rewards": [
                        {
                            "id": "h3",
                            "droplets": 500
                        }
                    ]
                }
            ]
        }
    ],
    "category": "swap",
    "filters": [
        "featured",
        "trending"
    ],
    "action_tags": [
        "swap",
        "add-liquidity",
        "create-pool"
    ]
}

=== aptree-labs/campaign-registry/campaigns/10.campaign.json
{
    "id": "10",
    "title": "Kofi Trophy",
    "description": "Stake and mint to lift the trophy; droplets raise the canopy lofty.",
    "start_at": 1754221472038,
    "end_at": 1785757217018,
    "status": "active",
    "platform": "kofi",
    "referral_link": "https://app.kofi.finance/mint",
    "functions": [
        {
            "entry_function": "0x2cc52445acc4c5e5817a0ac475976fbef966fedb6e30e7db792e10619c76181f::gateway::deposit_entry",
            "events": [ 
                {
                    "name": "0x2cc52445acc4c5e5817a0ac475976fbef966fedb6e30e7db792e10619c76181f::minting_manager::MintEvent",
                    "rewards": [
                        {
                            "id": "ko1",
                            "droplets": 200
                        }
                    ]
                }
            ]
        },
        {
            "entry_function": "0x2cc52445acc4c5e5817a0ac475976fbef966fedb6e30e7db792e10619c76181f::gateway::stake_entry",
            "events": [
                {
                    "name": "0x2cc52445acc4c5e5817a0ac475976fbef966fedb6e30e7db792e10619c76181f::staking_manager::StakeEvent",
                    "rewards": [
                        {
                            "id": "ko2",
                            "droplets": 500
                        }
                    ]
                }
            ]
        }
    ],
    "action_tags": [
        "mint",
        "stake"
    ]
}
